SDRA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        
    

admin.site.site_header = 'SDRA - LIFE'
admin.site.site_title = 'Life'
admin.site.index_title = 'Sistema de Registro de Atividades'

SRDA/SRDA/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import ChangePasswordView, CustomLoginView, Home, LocalList, AtividadeList, AtividadeGeralList

from core import  views as v
from . import views
from .views import (
     LocalCreate,
     AtividadeCreate,
     LocalUpdate,
     AtividadeUpdate,
     LocalDelete,
     AtividadeDelete,
     CustomLoginRedirectView,
     UsuarioCreate,
     
)
  # urls
urlpatterns = [
    # url de login e logout
    path('login/', CustomLoginView.as_view(
        template_name='core/usuarios/login.html'
    ), name="login"),
    path('custom_login_redirect/', CustomLoginRedirectView.as_view(),
         name='custom_login_redirect'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registrar/', UsuarioCreate.as_view(), name='registrar-usuario'),
    path('home/', Home.as_view(), name= 'home'),
    # create 
    path('cadastro-atividade/', AtividadeCreate.as_view(),
         name='cadastro-atividade'),
    path('cadastro-local/', LocalCreate.as_view(), name='cadastro-local'),
    # update 
    path('editar/local/<int:pk>', LocalUpdate.as_view(), name='editar-local'),
    path('editar/atividade/<int:pk>',
         AtividadeUpdate.as_view(), name='editar-atividade'),
    # delete 
    path('excluir/local/<int:pk>', LocalDelete.as_view(), name='excluir-local'),
    path('excluir/atividade/<int:pk>',
         AtividadeDelete.as_view(), name='excluir-atividade'),
    # list 
    path('listar/locais/', LocalList.as_view(), name='listar-local'),
    path('listar/atividades/', AtividadeList.as_view(), name='listar-atividade'),
    path('listar/atividadesGerais/', AtividadeGeralList.as_view(),
         name='listar-atividade-geral'),

    path('export-pdf/', views.export_pdf, name='export-pdf'),
    path('relatorio/<int:pk>/gerar_pdf/',
         views.gerar_pdf_relatorio, name='gerar-pdf-relatorio'),
    path('relatorio/<int:pk>/', views.exibir_relatorio, name='exibir-relatorio'),

    path('alterar-senha/', ChangePasswordView.as_view(), name='alterar_senha'),

    path('password_reset/', v.MyPasswordReset.as_view(), name='password_reset'),  # noqa E501
    path('password_reset/done/', v.MyPasswordResetDone.as_view(), name='password_reset_done'),  # noqa E501
    path('reset/<uidb64>/<token>/', v.MyPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', v.MyPasswordResetComplete.as_view(), name='password_reset_complete'),

]

core/models.py
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import Permission
from django.contrib.auth.models import Group
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def normalize_cpf(self, cpf):
        # Remove caracteres especiais
        cpf = ''.join(filter(str.isdigit, str(cpf)))

        # Verifica se o CPF possui 11 dígitos
        if len(cpf) != 11:
            raise ValueError('CPF deve conter 11 dígitos após a normalização')

        return cpf

    def _create_user(self, cpf, password, **extra_fields):
        if not cpf:
            raise ValueError('O cpf é obrigatório')

        cpf = self.normalize_cpf(cpf)
        user = self.model(cpf=cpf, username=cpf, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, cpf, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(cpf, password, **extra_fields)

    def create_superuser(self, cpf, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser=True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff=True')
        return self._create_user(cpf, password, **extra_fields)


class CustomUsuario(AbstractUser):
    cpf = models.CharField(max_length=14,
                           verbose_name=_('CPF'),
                           unique=True
                           )
    is_staff = models.BooleanField('Membro da equipe',
                                   default=False)

    USERNAME_FIELD = 'cpf'
    REQUIRED_FIELDS = ['first_name', 'last_name',]

    def __str__(self):
        return self.cpf
    
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    objects = UsuarioManager()


class Local(models.Model):
    nome = models.CharField(max_length=50)
    def __str__(self):
        return self.nome


class Atividade(models.Model):
    tema = models.CharField(max_length=50)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, 
                                on_delete=models.CASCADE
                                )
    descricao = models.TextField()
    local = models.ForeignKey(Local, on_delete=models.CASCADE)
    quantidade_ptc = models.PositiveIntegerField()
    data_inicio = models.DateField('Data de inicio')
    data_encerramento = models.DateField('Data de encerramento')
    duracao = models.CharField(max_length=20)
    data_registro = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.tema
    
    def get_usuario_nome_completo(self):
        return self.usuario.get_full_name() if self.usuario else "Usuário sem nome"

    def get_absolute_url(self):
        return reverse('exibir-relatorio', args=[str(self.id)])

    def save(self, *args, **kwargs):
        if not self.id:
            self.data_registro = timezone.now()
        super(Atividade, self).save(*args, **kwargs)


class Arquivo(models.Model):
    arquivo = models.FileField(upload_to='')
    Atividade = models.ForeignKey(
        Atividade, related_name='arquivo', 
        on_delete=models.CASCADE
        )

    def __str__(self):
        return self.arquivo.name

    def is_doc(self):
        return self.arquivo.name.lower().endswith('.doc') or self.arquivo.name.lower().endswith('.docx')

    def is_pdf(self):
        return self.arquivo.name.lower().endswith('.pdf')

    def is_image(self):
        return self.arquivo.name.lower().endswith('.png') or self.arquivo.name.lower().endswith('.jpg') or self.arquivo.name.lower().endswith('.jpeg') or self.arquivo.name.lower().endswith('.gif') or self.arquivo.name.lower().endswith('.bmp')

core/views.py
# Importações de módulos padrão
from django.contrib.auth.views import LoginView
from textwrap import fill
import logging
from django.contrib.auth.models import User
from .models import Atividade, Arquivo, CustomUsuario
from django.views.generic import TemplateView
from reportlab.platypus import FrameBreak
from reportlab.platypus import Image
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.platypus import Table, TableStyle, PageTemplate, Frame
from reportlab.lib.pagesizes import letter, landscape
from django.utils.timezone import now
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView)
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import FormView
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from datetime import timedelta
from django.shortcuts import render
from .models import Arquivo, Atividade
from datetime import datetime
from django.http import HttpResponse
import datetime
from django.utils import timezone
import tempfile
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Image, Table, TableStyle, Paragraph
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Spacer
from reportlab.platypus import KeepInFrame

# Importações do Django
from django.http import HttpResponse, request
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import Group
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
# Importações de módulos do Django específicos
from django.views.generic.edit import View, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .forms import ArquivoFormSet, CustomUsuarioCreateForm
from django.templatetags.static import static
from django.conf import settings
from django.forms import inlineformset_factory
from django.db.models import Q
import os
from braces.views import GroupRequiredMixin
from .models import Local, Atividade
from django.contrib.auth.mixins import LoginRequiredMixin
from dateutil.parser import parse
from datetime import timedelta, datetime
from django.contrib import messages

# views para registro de usuarios


class UsuarioCreate(CreateView):
    template_name = 'core/usuarios/form.html'
    form_class = CustomUsuarioCreateForm
    success_url = reverse_lazy('login')
    success_message = 'Usuário cadastrado com Sucesso!'

    def form_valid(self, form):

        grupo = get_object_or_404(Group, name="Docente")
        url = super().form_valid(form)
        self.object.groups.add(grupo)
        self.object.save()
        messages.success(self.request, self.success_message)

        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Cadastro de Usuário"
        context['botao'] = "Cadastrar"
        return context

# views para reset senha


class MyPasswordReset(PasswordResetView):
    template_name = 'core/usuarios/password_reset_form.html'
    ...


class MyPasswordResetDone(PasswordResetDoneView):

    template_name = 'core/usuarios/password_reset_done.html'
    ...


class MyPasswordResetConfirm(PasswordResetConfirmView):

    template_name = 'core/usuarios/password_reset_confirm.html'

    def form_valid(self, form):
        self.user.is_active = True
        self.user.save()
        messages.success(self.request, 'Sua senha foi atualizada com sucesso!')
        return super(MyPasswordResetConfirm, self).form_valid(form)


class MyPasswordResetComplete(PasswordResetCompleteView):

    template_name = 'core/usuarios/password_reset_complete.html'
    ...

# view para alterar senha


class ChangePasswordView(LoginRequiredMixin, FormView):
    template_name = 'core/usuarios/change_password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('listar-atividade')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        messages.success(self.request, 'Sua senha foi atualizada com sucesso!')
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Alterar Senha"
        context['botao'] = "Alterar minha Senha"
        context['url'] = reverse('listar-atividade')
        context['breadcrumb'] = [
            {'title': 'Inicio', 'url': '/home/'},
            {'title': 'alterar senha', 'url': '/alterar_senha/'},

        ]
        return context


class Home(TemplateView):
    template_name = 'core/home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumb'] = [
            {'title': 'Inicio', 'url': '/home/'},
        ]
        return context


class LocalCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Local
    fields = ['nome']
    template_name = 'core/registros/form.html'
    success_url = reverse_lazy('listar-local')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Cadastro de Local"
        context['botao'] = "Cadastrar"
        return context


class LocalUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Local
    fields = ['nome']
    template_name = 'core/registros/form.html'
    success_url = reverse_lazy('listar-local')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Editar Local"
        context['botao'] = "Salvar"
        context['url'] = reverse('listar-local')

        return context


class LocalDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Local
    template_name = 'core/registros/form_excluir.html'
    success_url = reverse_lazy('listar-local')


class LocalList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = [u"Administrador", u"Docente"]
    model = Local
    template_name = 'core/listas/Local.html'


class AtividadeCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Atividade
    fields = ['tema', 'descricao', 'local', 'quantidade_ptc',
              'data_inicio', 'data_encerramento', 'duracao']
    template_name = 'core/registros/form-upload.html'
    success_url = reverse_lazy('listar-atividade')
    success_message = 'Atividade registrada com Sucesso!'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Registro de Atividade"
        context['botao'] = "Registrar"
        context['url'] = reverse('listar-atividade')
        context['breadcrumb'] = [
            {'title': 'Inicio', 'url': '/home/'},
            {'title': 'Atividades', 'url': '/listar/atividades/'},
            {'title': 'Registro de atividade', 'url': '/cadastro-atividade/'},
        ]
        # Cria formset de Arquivos relacionados à Atividade
        ArquivoFormSet = inlineformset_factory(
            Atividade, Arquivo, fields=['arquivo',], extra=3)
        if self.request.POST:
            # Se dados forem submetidos, popula os formulários com os dados enviados
            context['formset'] = ArquivoFormSet(
                self.request.POST, self.request.FILES)
        else:
            # Se não, cria um formset vazio
            context['formset'] = ArquivoFormSet()
        return context
    # validação de formulario

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        url = super().form_valid(form)
        messages.success(self.request, self.success_message)
        # salva os arquivos associados à atividade
        formset = ArquivoFormSet(
            self.request.POST, self.request.FILES, instance=self.object)
        if formset.is_valid():
            formset.save()
        return url


class AtividadeUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Atividade
    fields = ['tema', 'descricao', 'local', 'quantidade_ptc',
              'data_inicio', 'data_encerramento', 'arquivo']
    template_name = 'core/registros/form-upload.html'
    success_url = reverse_lazy('listar-atividade')

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        self.object = get_object_or_404(
            Atividade, pk=pk, usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Editar Registro de Atividade"
        context['botao'] = "Salvar"
        context['url'] = reverse('listar-atividade')
        return context


class AtividadeDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Atividade
    template_name = 'core/registros/form_excluir.html'
    success_url = reverse_lazy('listar-atividade')

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        self.object = get_object_or_404(
            Atividade, pk=pk, usuario=self.request.user)

core/templates/core/registros/form-upload.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block titulo %}
<title>Registro</title>
{% endblock titulo %}

{% block main %}

{% include 'core/breadcrumb.html' %}

<div class="container-fluid col-10 mb-4 page-context-header" id="header-page">
  <div class="page-header-headings">
      <h1 class="h2" style="font-weight: 700;">{{ titulo }}</h1>
  </div>
</div>

<div class="container col-10 mb-3" id="conteudoForm">

  <form method="POST" action="{% url 'cadastro-atividade' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3 form-group">
      <label for="{{ form.tema.id_for_label }} floatingInput" class="form-label mt-3" id="label-form">Tema:</label>
      {{ form.tema|add_class:"form-control"}}
    </div>

    <div class="mb-3 form-group">
      <label for="{{ form.descricao.id_for_label }}" class="form-label" id="label-form">Descrição:</label>
      <textarea name="{{ form.descricao.name }}" id="{{ form.descricao.id_for_label }}" class="form-control" rows="3"></textarea>
    </div>

    <div class="mb-3 form-group">
      <label for="{{ form.local.id_for_label }}" class="form-label" id="label-form">Local:</label>
      {{ form.local|add_class:"form-select" }}
    </div>

    <div class="mb-3 form-group">
      <label for="{{ form.quantidade_ptc.id_for_label }}" class="form-label" id="label-form">Quantidade de Participantes:</label>
      {{ form.quantidade_ptc|add_class:"form-control" }}
    </div>

    <div class="mb-3 row">
      <div class="col-md-6 form-group">
        <label for="{{ form.data_inicio.id_for_label }}" class="form-label" id="label-form">Data de Início:</label>
        {{ form.data_inicio|add_class:"form-control"|attr:"type:date" }}
      </div>

      <div class="col-md-6 form-group">
        <label for="{{ form.data_encerramento.id_for_label }}" class="form-label" id="label-form">Data de Encerramento:</label>
        {{ form.data_encerramento|add_class:"form-control"|attr:"type:date"}}
      </div>
    </div>
    <div class=" mb-3 form-group">
      <label for="{{ form.duracao.id_for_label }}" class="form-label" id="label-form">Duração da atividade:  <span style="font-style: italic; font-size: 11px; font-weight:0; color: gray;">(em horas)</span></label>
      {{ form.duracao|add_class:"form-control"}}
    </div>
    {{ formset.management_form }}
    <div class=" form-group">
      <label for="{{ formset.arquivo.id_for_label }}" class="form-label" id="label-form">Faça upload de arquivos ou imagens relacionados a atividade </label>
      <span class="lead-sx dark" disable>(Opcional)</span>
    </div>
    
    {% for arquivo_form in formset %}
    <div class=" mb-3 form-group">
      {{ arquivo_form.arquivo|add_class:"form-control"}}
    </div>
        
    {% endfor %}

    <button type="submit" id="submit-button" class="btn btn-success mb-3 register">{{ botao }}</button>
    <a href="{{ url }}" class="btn btn-danger mb-3 cancel">Cancelar</a>
  </form>
</div>
{% endblock main %}
{% block footer %}
<footer id="rodape" class="text-center text-white">
  <div class="container-fluid p-3">
    © 2023 Copyright: Felipe dos Santos & Alexandre Lira
  </div>
</footer>
{% endblock footer %}

<!-- {% block scripts %}
<script src="{% static 'js/jquery-3.6.4.min.js' %}"></script> 
<script>
    $(document).ready(function() {
      
        $('#add-form').on('click', function() {
            var form_idx = $('div input[type="file"]').length;
            var new_form = $('#id_arquivo-TOTAL_FORMS').val(form_idx + 1);
            var new_input = '<div> <input type="file" class="form-control mt-3" name="arquivos-' + form_idx + '-arquivo" id="id_arquivos-' + form_idx + '-arquivo" multiple></div>';
            $(this).before(new_input);
        });
    });

    $(document).on('click', '.delete-form', function () {
    $(this).parent().remove();
    form_idx--;
    $('#id_arquivos-TOTAL_FORMS').val(form_idx);

    $('#submit-button').on('click', function(event) {
            event.preventDefault(); // Impede o envio padrão do formulário

            // Validação manual do formulário
            var form = $('form')[0];
            if (!form.checkValidity()) {
                window.alert('Por favor, preencha todos os campos corretamente.');
                return false;
            }

            // Se a validação for bem-sucedida, envie o formulário
            form.submit();
        });
});
</script> -->
{% endblock scripts %}

core/templates/core/registros/form.html
{% extends "core/base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block main %}
<div class="container">
    <h3 style="margin-top: 15px ;">{{titulo}}</h3>

    <hr>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-success">{{ botao }}</button>
        <a href="{{ url }}" class="btn btn-danger">Cancelar</a>
    </form>
</div>
{% endblock main %}
{% block footer %}
<footer id="rodape" class="text-center text-white">
    <div class="container-fluid  p-3 ">
        © 2023 Copyright: Felipe dos Santos & Alexandre Lira
    </div>
</footer>
{% endblock footer %}

core/templates/core/registros/form_excluir.html
{% extends "core/base.html" %}
{% load static %}

{% block main %}
  <h3 style="margin-top: 15px ;">Excluir Registro</h3>

  <p class="lead">
    Confirme para excluir resgistro
  </p>
  <hr>

  <form action="" method="POST">

    <P>
        Deseja excluir o registro <b>{{object}} </b>?
    </P>
    {% csrf_token %}

    {{form.as_p}}

    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'listar-atividade'%}" class="btn btn-primary">Cancelar</a>
  </form>
{% endblock main %}